In [4]:
%display latex
A = Matrix([[3,-2], [-3, 1], [-1,4]]); show('A = ', A)
b = vector([6,1,9]); show('b = ', b.column())

'A = ' [ 3 -2]
[-3  1]
[-1  4]

'b = ' [6]
[1]
[9]

In [20]:
AT = A.transpose()
pseudo_inverse = (AT * A).inverse()*AT
show('Pseudo inverse matrix: ', pseudo_inverse)
x = pseudo_inverse*b
show('x = ', x, ' = ', n(x, digits=3))

'Pseudo inverse matrix: ' [37/230  -5/23 31/230]
[ 1/230  -2/23 63/230]

'x = ' (451/230, 553/230) ' = ' (1.96, 2.40)

In [25]:
n((A*x - b).norm()^2, digits=3)

46.1

In [31]:
X = Matrix([[1, 2],
            [1, 5],
            [1, 7],
            [1, 8]])
y = vector([1, 2, 3, 3])
beta = (X.transpose()*X).inverse()*X.transpose() * y
n(beta, digits=3)

(0.286, 0.357)

In [78]:
for order in range(10):
    X = Matrix([[x^n for n in range(order+1)] for x in range(6)])
    y = vector([1, 6, 7, 3, 5, 9])
    show(X)
    XT = X.transpose(); show(XT)
    show(XT*X)
    show((XT*X).determinant())
    XTX_inv = (XT * X).inverse()
    p_i_matrix =  XTX_inv * XT
    beta =  p_i_matrix * y
    beta_approx = n(beta, digits=3)
    residuals = n((y-X*beta).norm(), digits=3)
    print(f'{order} order fitting resulted in the following coefficients({beta_approx}) with a residual of {residuals}')

[1]
[1]
[1]
[1]
[1]
[1]

[1 1 1 1 1 1]

[6]

6

0 order fitting resulted in the following coefficients((5.17)) with a residual of 6.39


[1 0]
[1 1]
[1 2]
[1 3]
[1 4]
[1 5]

[1 1 1 1 1 1]
[0 1 2 3 4 5]

[ 6 15]
[15 55]

105

1 order fitting resulted in the following coefficients((2.81, 0.943)) with a residual of 5.03


[ 1  0  0]
[ 1  1  1]
[ 1  2  4]
[ 1  3  9]
[ 1  4 16]
[ 1  5 25]

[ 1  1  1  1  1  1]
[ 0  1  2  3  4  5]
[ 0  1  4  9 16 25]

[  6  15  55]
[ 15  55 225]
[ 55 225 979]

3920

2 order fitting resulted in the following coefficients((2.75, 1.03, -0.0179)) with a residual of 5.03


[  1   0   0   0]
[  1   1   1   1]
[  1   2   4   8]
[  1   3   9  27]
[  1   4  16  64]
[  1   5  25 125]

[  1   1   1   1   1   1]
[  0   1   2   3   4   5]
[  0   1   4   9  16  25]
[  0   1   8  27  64 125]

[    6    15    55   225]
[   15    55   225   979]
[   55   225   979  4425]
[  225   979  4425 20515]

254016

3 order fitting resulted in the following coefficients((1.00, 9.02, -4.39, 0.583)) with a residual of 1.79


[  1   0   0   0   0]
[  1   1   1   1   1]
[  1   2   4   8  16]
[  1   3   9  27  81]
[  1   4  16  64 256]
[  1   5  25 125 625]

[  1   1   1   1   1   1]
[  0   1   2   3   4   5]
[  0   1   4   9  16  25]
[  0   1   8  27  64 125]
[  0   1  16  81 256 625]

[     6     15     55    225    979]
[    15     55    225    979   4425]
[    55    225    979   4425  20515]
[   225    979   4425  20515  96825]
[   979   4425  20515  96825 462979]

20901888

4 order fitting resulted in the following coefficients((0.893, 10.8, -6.31, 1.21, -0.0625)) with a residual of 1.70


[   1    0    0    0    0    0]
[   1    1    1    1    1    1]
[   1    2    4    8   16   32]
[   1    3    9   27   81  243]
[   1    4   16   64  256 1024]
[   1    5   25  125  625 3125]

[   1    1    1    1    1    1]
[   0    1    2    3    4    5]
[   0    1    4    9   16   25]
[   0    1    8   27   64  125]
[   0    1   16   81  256  625]
[   0    1   32  243 1024 3125]

[       6       15       55      225      979     4425]
[      15       55      225      979     4425    20515]
[      55      225      979     4425    20515    96825]
[     225      979     4425    20515    96825   462979]
[     979     4425    20515    96825   462979  2235465]
[    4425    20515    96825   462979  2235465 10874275]

1194393600

5 order fitting resulted in the following coefficients((1.00, -1.73, 15.2, -11.0, 2.75, -0.225)) with a residual of 0.000


[    1     0     0     0     0     0     0]
[    1     1     1     1     1     1     1]
[    1     2     4     8    16    32    64]
[    1     3     9    27    81   243   729]
[    1     4    16    64   256  1024  4096]
[    1     5    25   125   625  3125 15625]

[    1     1     1     1     1     1]
[    0     1     2     3     4     5]
[    0     1     4     9    16    25]
[    0     1     8    27    64   125]
[    0     1    16    81   256   625]
[    0     1    32   243  1024  3125]
[    0     1    64   729  4096 15625]

[        6        15        55       225       979      4425     20515]
[       15        55       225       979      4425     20515     96825]
[       55       225       979      4425     20515     96825    462979]
[      225       979      4425     20515     96825    462979   2235465]
[      979      4425     20515     96825    462979   2235465  10874275]
[     4425     20515     96825    462979   2235465  10874275  53201625]
[    20515     96825    462979   2235465  10874275  53201625 261453379]

0

ZeroDivisionError: matrix must be nonsingular

In [74]:
%display plain
import numpy as np
x = range(6)
y = vector([1, 6, 7, 3, 5, 9])
np.polyfit(x, y, deg=5, full=True)

(array([ -0.225     ,   2.75      , -11.04166667,  15.25      ,
         -1.73333333,   1.        ]),
 array([], dtype=float64),
 6,
 array([2.30229671e+00, 7.83902797e-01, 2.83879264e-01, 6.52030433e-02,
        9.32802330e-03, 6.07147469e-04]),
 1.3322676295501878e-15)